import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { glClass, money, signedMoney, signedPct } from "../lib/format";
// Canvas 2a: net worth, movers, market pulse.
export function Home({ rows, totals, baseCurrency, onOpen, onAdd }) {
    if (rows.length === 0) {
        return (_jsxs("div", { className: "empty", children: [_jsx("p", { style: { marginBottom: 14 }, children: "No runners on the track." }), _jsx("button", { className: "btn", onClick: onAdd, children: "Add your first position" })] }));
    }
    const movers = [...rows].filter((r) => r.change_pct !== null)
        .sort((a, b) => Math.abs(b.change_pct ?? 0) - Math.abs(a.change_pct ?? 0)).slice(0, 3);
    return (_jsxs(_Fragment, { children: [_jsxs("section", { "aria-label": "Net worth", style: { margin: "8px 0 18px" }, children: [_jsx("div", { className: "net num", "data-testid": "net-worth", children: money(totals.value, baseCurrency) }), _jsxs("div", { className: `day num ${glClass(totals.gl)}`, "data-testid": "total-gl", children: [signedMoney(totals.gl, baseCurrency), " all time"] }), _jsx("div", { className: "countdown", "aria-hidden": "true", children: _jsx("div", { style: { width: "38%" } }) })] }), _jsx("h2", { className: "h1", style: { fontSize: 16 }, children: "Movers" }), _jsx("div", { className: "card", style: { marginBottom: 16 }, children: movers.map((r) => (_jsxs("button", { className: "row", onClick: () => onOpen(r.holding_id), children: [_jsxs("span", { children: [_jsx("span", { className: "sym", children: r.symbol }), " ", _jsx("span", { className: "sub", children: r.name })] }), _jsx("span", { className: `num right ${glClass(r.change_pct)}`, children: signedPct(r.change_pct) })] }, r.holding_id))) }), _jsx("h2", { className: "h1", style: { fontSize: 16 }, children: "Positions" }), _jsx("div", { className: "card", children: rows.map((r) => (_jsxs("button", { className: "row", onClick: () => onOpen(r.holding_id), children: [_jsxs("span", { children: [_jsx("span", { className: "sym", children: r.symbol }), _jsx("br", {}), _jsxs("span", { className: "sub", children: [r.qty ?? 0, " sh"] })] }), _jsxs("span", { className: "right", children: [_jsx("span", { className: "num", children: money(r.value, r.currency) }), _jsx("br", {}), _jsx("span", { className: `num sub ${glClass(r.total_gl)}`, children: signedMoney(r.total_gl, r.currency) })] })] }, r.holding_id))) })] }));
}
