-- AI insights: hourly, per held symbol, generated by MARA Cloud (MiniMax M2.7).
create table if not exists public.insights (
  symbol text primary key references public.symbols(symbol) on delete cascade,
  bullets jsonb not null,                -- 3-5 succinct takes, 7-day news focus
  windows jsonb,                         -- {d7,d30,d60,y1,y2}: one-line context per horizon
  model text not null,
  generated_at timestamptz not null default now()
);
alter table public.insights enable row level security;
create policy "insights readable" on public.insights for select to authenticated using (true);
grant select on public.insights to authenticated, service_role;

-- Edge functions read the API key through this (vault is not exposed over the data API).
create or replace function public.get_secret(secret_name text) returns text
language plpgsql security definer set search_path = public as $$
declare v text;
begin
  select decrypted_secret into v from vault.decrypted_secrets where name = secret_name;
  return v;
end $$;
revoke all on function public.get_secret(text) from public, anon, authenticated;
grant execute on function public.get_secret(text) to service_role;

select cron.schedule('assetly-insights-sync', '7 * * * *', $$select public.invoke_edge('insights-sync')$$);
